#!/usr/bin/env python3
"""Generate military_jet.stl - a low-poly fighter jet (F-16 style, ~15 m long).

The mesh mirrors the geometry built by MilitaryJet.bas so you can either run
the macro inside SolidWorks or import this STL directly
(File > Open > *.stl, import as Solid Body or Graphics Body).

No third-party dependencies; coordinates are modeled in metres and written
out in millimetres (the unit SolidWorks assumes for STL by default).

    python3 generate_jet_stl.py          # writes military_jet.stl
"""
import math
import struct

SCALE = 1000.0  # metres -> millimetres

triangles = []  # list of ((x,y,z), (x,y,z), (x,y,z))


def tri(a, b, c):
    triangles.append((a, b, c))


def quad(a, b, c, d):
    """Split quad a-b-c-d (in winding order) into two triangles."""
    tri(a, b, c)
    tri(a, c, d)


# ---------------------------------------------------------------------------
# Fuselage: circular cross-sections lofted along X, closed with a nose point
# and a flat tail cap (engine nozzle).  x = length, y = up, z = span.
# ---------------------------------------------------------------------------
STATIONS = [  # (x, radius) in metres
    (0.0, 0.04),
    (0.8, 0.28),
    (2.0, 0.50),
    (4.0, 0.72),
    (6.0, 0.80),
    (9.0, 0.80),
    (11.0, 0.78),
    (12.5, 0.68),
    (14.0, 0.52),
    (15.0, 0.38),
]
SIDES = 16


def ring(x, r):
    pts = []
    for i in range(SIDES):
        a = 2.0 * math.pi * i / SIDES
        pts.append((x, r * math.sin(a), r * math.cos(a)))
    return pts


rings = [ring(x, r) for x, r in STATIONS]

nose = (-0.15, 0.0, 0.0)
for i in range(SIDES):
    tri(nose, rings[0][i], rings[0][(i + 1) % SIDES])

for ra, rb in zip(rings, rings[1:]):
    for i in range(SIDES):
        j = (i + 1) % SIDES
        quad(ra[i], rb[i], rb[j], ra[j])

tail_center = (STATIONS[-1][0], 0.0, 0.0)
for i in range(SIDES):
    tri(tail_center, rings[-1][(i + 1) % SIDES], rings[-1][i])


# ---------------------------------------------------------------------------
# Prism helper: convex polygon extruded symmetrically about an offset plane.
# ---------------------------------------------------------------------------
def prism(polygon, thickness, axis, offset=0.0):
    """polygon: list of 2D points (convex, CCW) in the plane normal to `axis`.
    axis: 'y' -> polygon is (x, z) planform; 'z' -> polygon is (x, y) profile.
    """
    h = thickness / 2.0

    def lift(p, w):
        if axis == "y":
            return (p[0], offset + w, p[1])
        return (p[0], p[1], offset + w)

    top = [lift(p, +h) for p in polygon]
    bot = [lift(p, -h) for p in polygon]

    # caps (fan triangulation, valid for convex polygons)
    for i in range(1, len(polygon) - 1):
        tri(top[0], top[i], top[i + 1])
        tri(bot[0], bot[i + 1], bot[i])
    # side walls
    n = len(polygon)
    for i in range(n):
        j = (i + 1) % n
        quad(top[i], bot[i], bot[j], top[j])


# Delta wings (planform in x/z, thin in y)
prism(
    [(5.8, 0.0), (9.9, 4.6), (10.8, 4.6), (10.8, -4.6), (9.9, -4.6)],
    thickness=0.12,
    axis="y",
)

# Horizontal stabilizers
prism(
    [(11.5, 0.0), (13.8, 2.4), (14.5, 2.4), (14.5, -2.4), (13.8, -2.4)],
    thickness=0.09,
    axis="y",
    offset=0.05,
)

# Vertical tail fin (profile in x/y, thin in z)
prism(
    [(11.2, 0.5), (12.9, 3.0), (13.9, 3.0), (14.5, 0.5)],
    thickness=0.12,
    axis="z",
)

# Canopy (faceted bubble over the cockpit)
prism(
    [(2.6, 0.3), (6.3, 0.4), (5.1, 1.1), (3.3, 1.1)],
    thickness=0.7,
    axis="z",
)


# ---------------------------------------------------------------------------
# Write binary STL
# ---------------------------------------------------------------------------
def normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / length, ny / length, nz / length


def main():
    out = "military_jet.stl"
    with open(out, "wb") as f:
        f.write(b"military jet - generated by generate_jet_stl.py".ljust(80, b"\0"))
        f.write(struct.pack("<I", len(triangles)))
        for a, b, c in triangles:
            f.write(struct.pack("<3f", *normal(a, b, c)))
            for p in (a, b, c):
                f.write(struct.pack("<3f", p[0] * SCALE, p[1] * SCALE, p[2] * SCALE))
            f.write(struct.pack("<H", 0))
    print(f"wrote {out}: {len(triangles)} triangles")


if __name__ == "__main__":
    main()
